### ISSUE TITLE
publish: Add slash command localization

### ISSUE THREAD

**Issue by SrIzan10** [sern-handler/awesome-plugins#37]
# Why

It makes it more accessible to people (and I need it for a discord bot as it's going to be multilanguage.

# Possible solutions

Add it to the options where you start up publish.

**Comment by SrIzan10** [comment]
i cnat add labels 💀

**Comment by EvolutionX-10** [comment]
It depends on whether **sern** provides it in module or not, and as far as I know, it does not provide it on a top level, and only provides for options (which is successfully passed into publish plugin data) so this really comes down to [handler](https://github.com/sern-handler/handler).
It would be good if you can open issue there instead of here, so that @jacoobes will remember that, once done you can re-open this issue to notify me for the update to the plugin.
Thanks!
